code/account/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView


from .views import(
                EmailVerificationView,
                DashBoardHomeView,
                UrlDetailView,
                UrlListView
            )


app_name = 'Account'

urlpatterns = [

    re_path('email/verify/(?P<key>[0-9A-Za-z]+)/',
            EmailVerificationView.as_view(),
            name='verify_email'),

    path('detail/<pk>/', UrlDetailView.as_view(), name='url_detail'),
    path('', UrlListView.as_view(), name='dashboard'),
]

code/urlshortener/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import LoginView, LogoutView

from account.views import EmailVerificationView, SignUpView

urlpatterns = [
    path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    re_path('email/verify/(?P<key>[0-9A-Za-z]+)/', 
            EmailVerificationView.as_view(), 
            name='verify_email'),

    path('dashboard/', include('account.urls', namespace = 'account')),
    path('', include('shortener.urls', namespace = 'shortener'))
]

code/templates/dashboard/detail.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
  <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
      <p>{{object.url}}</p><hr>
      <p>{% trans "Condensed Url" %} - {{object.get_condensed_url}}</p>
      <p>{% trans "Created on" %} {{object.timestamp|date:"M d, Y"}}</p>
      <p>{% trans "Number of visits" %} - {{object.urlviews.count}}</p>
      <p>{% trans "list of Ip's" %} - {{object.urlviews.ip_address}}</p>
    </div>
  </div>

{% endblock %}

code/templates/dashboard/list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <div class='row'>
    <div class='col-md-12'>
      <h1>{% trans "List Of Url Condensed" %}</h1>
      <div class="panel-group">
        {% for data in object_list %}
        <a href="{% url 'account:url_detail' data.pk %}">
          <div class="panel panel-default">
            <div class="panel-body">
              <p>{% trans "Parent url" %} - {{data.url}}</p>
              <p>{% trans "Condensed url" %} - {{data.get_condensed_url}}</p>
              <p>{% trans "Date Created" %} - {{data.timestamp|date:"M d, Y"}}.</p>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
  </div>

{% endblock %}